### ISSUE TITLE
Error processing example bag dataset - process has died, exit code -11

### ISSUE THREAD

**Issue by kubiak54** [uzh-rpg/rpg_svo#114]
Hello,
first I would love to say I really appreciate your work a lot, its amazing.
I am trying to process example bag dataset but getting error:

GDB:
jakub@jakub-iMac:~/catkin_ws$ roslaunch svo_ros test_rig3.launch
... logging to /home/jakub/.ros/log/5db750ac-605b-11e5-b499-c8bcc8bca74e/roslaunch-jakub-iMac-4966.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jakub-iMac:60122/

SUMMARY
========

CLEAR PARAMETERS
 * /svo/

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.13
 * /svo/cam_cx: 0.45905
 * /svo/cam_cy: 0.510056
 * /svo/cam_d0: 0.932
 * /svo/cam_fx: 0.509326
 * /svo/cam_fy: 0.796651
 * /svo/cam_height: 480
 * /svo/cam_model: ATAN
 * /svo/cam_topic: /camera/image_raw
 * /svo/cam_width: 752
 * /svo/grid_size: 30
 * /svo/init_rx: 3.14
 * /svo/init_ry: 0.0
 * /svo/init_rz: 0.0
 * /svo/loba_num_iter: 0
 * /svo/max_n_kfs: 10

NODES
  /
    svo (svo_ros/vo)

auto-starting new master
process[master]: started with pid [4978]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5db750ac-605b-11e5-b499-c8bcc8bca74e
process[rosout-1]: started with pid [4991]
started core service [/rosout]
process[svo-2]: started with pid [5009]
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/jakub/catkin_ws/devel/lib/svo_ros/vo...done.
Starting program: /home/jakub/catkin_ws/devel/lib/svo_ros/vo __name:=svo __log:=/home/jakub/.ros/log/5db750ac-605b-11e5-b499-c8bcc8bca74e/svo-2.log
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffe3b09700 (LWP 5016)]
[New Thread 0x7fffe3308700 (LWP 5017)]
[New Thread 0x7fffe2b07700 (LWP 5018)]
[New Thread 0x7fffe2306700 (LWP 5023)]
create vo_node
[ WARN] [1442838124.986085251]: Cannot find value for parameter: svo/publish_img_pyr_level, assigning default: 0
[ WARN] [1442838124.986708186]: Cannot find value for parameter: svo/publish_every_nth_img, assigning default: 1
[ WARN] [1442838124.987248364]: Cannot find value for parameter: svo/publish_every_nth_dense_input, assigning default: 1
[ WARN] [1442838124.988408761]: Cannot find value for parameter: svo/publish_world_in_cam_frame, assigning default: 1
[ WARN] [1442838124.989024074]: Cannot find value for parameter: svo/publish_map_every_frame, assigning default: 0
[ WARN] [1442838124.989633397]: Cannot find value for parameter: svo/publish_point_display_time, assigning default: 0
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffc5ed7700 (LWP 5039)]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[ WARN] [1442838125.398413628]: Cannot find value for parameter: svo/publish_markers, assigning default: 1
[ WARN] [1442838125.399008114]: Cannot find value for parameter: svo/publish_dense_input, assigning default: 0
[ WARN] [1442838125.399545228]: Cannot find value for parameter: svo/accept_console_user_input, assigning default: 1
[New Thread 0x7fffc5044700 (LWP 5092)]
[ INFO] [1442838125.400836639]: Found parameter: svo/cam_model, value: ATAN
[ INFO] [1442838125.401417375]: Found parameter: svo/cam_width, value: 752
[ INFO] [1442838125.401956311]: Found parameter: svo/cam_height, value: 480
[ INFO] [1442838125.402561824]: Found parameter: svo/cam_fx, value: 0.509326
[ INFO] [1442838125.403216737]: Found parameter: svo/cam_fy, value: 0.796651
[ INFO] [1442838125.403779855]: Found parameter: svo/cam_cx, value: 0.45905
[ INFO] [1442838125.404441168]: Found parameter: svo/cam_cy, value: 0.510056
[ INFO] [1442838125.404989513]: Found parameter: svo/cam_d0, value: 0.932
[ WARN] [1442838125.405534878]: Cannot find value for parameter: svo/init_tz, assigning default: 0
[ WARN] [1442838125.406142702]: Cannot find value for parameter: svo/init_ty, assigning default: 0
[ WARN] [1442838125.406798277]: Cannot find value for parameter: svo/init_tx, assigning default: 0
[ INFO] [1442838125.407350435]: Found parameter: svo/init_rz, value: 0
[ INFO] [1442838125.407889343]: Found parameter: svo/init_ry, value: 0
[ INFO] [1442838125.408436646]: Found parameter: svo/init_rx, value: 3.14
[ WARN] [1442838125.409056432]: Cannot find value for parameter: svo/trace_name, assigning default: svo
[ WARN] [1442838125.409681614]: Cannot find value for parameter: svo/trace_dir, assigning default: /tmp
[ WARN] [1442838125.410263133]: Cannot find value for parameter: svo/n_pyr_levels, assigning default: 3
[ WARN] [1442838125.410814209]: Cannot find value for parameter: svo/use_imu, assigning default: 0
[ WARN] [1442838125.411392713]: Cannot find value for parameter: svo/core_n_kfs, assigning default: 3
[ WARN] [1442838125.411982327]: Cannot find value for parameter: svo/map_scale, assigning default: 1
[ INFO] [1442838125.412483624]: Found parameter: svo/grid_size, value: 30
[ WARN] [1442838125.412983068]: Cannot find value for parameter: svo/init_min_disparity, assigning default: 50
[ WARN] [1442838125.413480968]: Cannot find value for parameter: svo/init_min_tracked, assigning default: 50
[ WARN] [1442838125.413984810]: Cannot find value for parameter: svo/init_min_inliers, assigning default: 40
[ WARN] [1442838125.414477118]: Cannot find value for parameter: svo/klt_max_level, assigning default: 4
[ WARN] [1442838125.414998253]: Cannot find value for parameter: svo/klt_min_level, assigning default: 2
[ WARN] [1442838125.415486373]: Cannot find value for parameter: svo/reproj_thresh, assigning default: 2
[ WARN] [1442838125.415971411]: Cannot find value for parameter: svo/poseoptim_thresh, assigning default: 2
[ WARN] [1442838125.416450716]: Cannot find value for parameter: svo/poseoptim_num_iter, assigning default: 10
[ WARN] [1442838125.416957010]: Cannot find value for parameter: svo/structureoptim_max_pts, assigning default: 20
[ WARN] [1442838125.417460952]: Cannot find value for parameter: svo/structureoptim_num_iter, assigning default: 5
[ WARN] [1442838125.417964788]: Cannot find value for parameter: svo/loba_thresh, assigning default: 2
[ WARN] [1442838125.418461348]: Cannot find value for parameter: svo/loba_robust_huber_width, assigning default: 1
[ INFO] [1442838125.418953029]: Found parameter: svo/loba_num_iter, value: 0
[ WARN] [1442838125.419438619]: Cannot find value for parameter: svo/kfselect_mindist, assigning default: 0.12
[ WARN] [1442838125.419931164]: Cannot find value for parameter: svo/triang_min_corner_score, assigning default: 20
[ WARN] [1442838125.420545096]: Cannot find value for parameter: svo/triang_half_patch_size, assigning default: 4
[ WARN] [1442838125.421085745]: Cannot find value for parameter: svo/subpix_n_iter, assigning default: 10
[ INFO] [1442838125.421628700]: Found parameter: svo/max_n_kfs, value: 10
[ WARN] [1442838125.422169615]: Cannot find value for parameter: svo/img_imu_delay, assigning default: 0
[ WARN] [1442838125.422713064]: Cannot find value for parameter: svo/max_fts, assigning default: 120
[ WARN] [1442838125.423324385]: Cannot find value for parameter: svo/quality_min_fts, assigning default: 50
[ WARN] [1442838125.423985939]: Cannot find value for parameter: svo/quality_max_drop_fts, assigning default: 40
[ INFO] [1442838125.424084097]: SVO initialized
[New Thread 0x7fffc4843700 (LWP 5136)]
[ INFO] [1442838125.425320509]: Found parameter: svo/cam_topic, value: /camera/image_raw
[ INFO] [1442838128.179397006]: RESET

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff737b282 in cv::Mat::copyTo(cv::_OutputArray const&) const ()
   from /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4
(gdb) bt
#0  0x00007ffff737b282 in cv::Mat::copyTo(cv::_OutputArray const&) const ()
   from /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4
#1  0x00007ffff7096563 in svo::FrameHandlerMono::addImage(cv::Mat const&, double) () from /home/jakub/catkin_ws/devel/lib/libsvo.so
#2  0x000000000040b6ca in svo::VoNode::imgCb (this=0x7fffffffd6b0, msg=...)
    at /home/jakub/catkin_ws/src/rpg_svo/svo_ros/src/vo_node.cpp:107
#3  0x00007fffc52948c9 in image_transport::RawSubscriber::internalCallback(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::function<void (boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)> const&) () from /opt/ros/indigo/lib//libimage_transport_plugins.so
#4  0x00007ffff797ce6c in boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const>) ()
   from /opt/ros/indigo/lib/libimage_transport.so
#5  0x00007fffc5299311 in ros::SubscriptionCallbackHelperT<boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) ()
   from /opt/ros/indigo/lib//libimage_transport_plugins.so
#6  0x00007ffff69b99c5 in ros::SubscriptionQueue::call() ()
   from /opt/ros/indigo/lib/libroscpp.so
#7  0x00007ffff6977777 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*---Type <return> to continue, or q <return> to quit---
) () from /opt/ros/indigo/lib/libroscpp.so
#8  0x00007ffff6978583 in ros::CallbackQueue::callAvailable(ros::WallDuration)
    () from /opt/ros/indigo/lib/libroscpp.so
#9  0x00007ffff69a4b15 in ros::spinOnce() ()
   from /opt/ros/indigo/lib/libroscpp.so
#10 0x000000000040aec0 in main (argc=1, argv=<optimized out>)
    at /home/jakub/catkin_ws/src/rpg_svo/svo_ros/src/vo_node.cpp:175
(gdb) 

I am running Ubuntu 14.04 and ROS Indigo.
It would be awesome if you could help me with running SVO without ROS as well.
I am able to get this:

jakub@jakub-iMac:~/Desktop/rpg_svo/svo/bin$ ./test_pipeline
[INFO] SVO initialized
reading image /home/jakub/Desktop/Datasets/sin2_tex2_h1_v8_d/img/frame_000002_0.png
[INFO] RESET
[INFO] Init: Selected first frame.
Frame-Id: 0 	#Features: 0 	Proc. Time: 26.107ms 
[INFO] Init: KLT tracked 565 features
[INFO] Init: KLT 25.3823px average disparity.
Frame-Id: 1 	#Features: 0 	Proc. Time: 35.289ms 
[INFO] Init: KLT tracked 543 features
[INFO] Init: KLT 50.8035px average disparity.
[INFO] Init: Homography RANSAC 543 inliers.
[INFO] Init: Selected second frame, triangulated initial map.
Frame-Id: 2 	#Features: 498 	Proc. Time: 47.925ms 
Frame-Id: 3 	#Features: 121 	Proc. Time: 4.881ms 
Frame-Id: 4 	#Features: 121 	Proc. Time: 1.844ms 
Frame-Id: 5 	#Features: 121 	Proc. Time: 2.03ms 
Frame-Id: 6 	#Features: 121 	Proc. Time: 2.069ms 
Frame-Id: 7 	#Features: 121 	Proc. Time: 1.943ms 
Frame-Id: 8 	#Features: 121 	Proc. Time: 2.057ms 
Frame-Id: 9 	#Features: 121 	Proc. Time: 2.015ms 
Frame-Id: 10 	#Features: 121 	Proc. Time: 2.163ms 
Frame-Id: 11 	#Features: 121 	Proc. Time: 2.083ms 
Frame-Id: 12 	#Features: 121 	Proc. Time: 2.12ms 
Frame-Id: 13 	#Features: 121 	Proc. Time: 2.259ms 
Frame-Id: 14 	#Features: 121 	Proc. Time: 2.484ms 
Frame-Id: 15 	#Features: 121 	Proc. Time: 2.136ms 
Frame-Id: 16 	#Features: 121 	Proc. Time: 2.49ms 
Frame-Id: 17 	#Features: 121 	Proc. Time: 2.031ms 
Frame-Id: 18 	#Features: 121 	Proc. Time: 2.607ms 
Frame-Id: 19 	#Features: 121 	Proc. Time: 2.31ms 
Frame-Id: 20 	#Features: 121 	Proc. Time: 2.134ms 
Frame-Id: 21 	#Features: 121 	Proc. Time: 2.186ms 
Frame-Id: 22 	#Features: 121 	Proc. Time: 2.066ms 
Frame-Id: 23 	#Features: 121 	Proc. Time: 2.538ms 
Frame-Id: 24 	#Features: 121 	Proc. Time: 2.31ms 
Frame-Id: 25 	#Features: 121 	Proc. Time: 2.149ms 
Frame-Id: 26 	#Features: 121 	Proc. Time: 2.389ms 
Frame-Id: 27 	#Features: 121 	Proc. Time: 2.078ms 
Frame-Id: 28 	#Features: 121 	Proc. Time: 2.348ms 
Frame-Id: 29 	#Features: 121 	Proc. Time: 2.092ms 
Frame-Id: 30 	#Features: 121 	Proc. Time: 2.081ms 
Frame-Id: 31 	#Features: 121 	Proc. Time: 2.197ms 
Frame-Id: 32 	#Features: 121 	Proc. Time: 2.696ms 
Frame-Id: 33 	#Features: 121 	Proc. Time: 2.133ms 
Frame-Id: 34 	#Features: 121 	Proc. Time: 2.325ms 
Frame-Id: 35 	#Features: 121 	Proc. Time: 2.657ms 
Frame-Id: 36 	#Features: 121 	Proc. Time: 2.347ms 
Frame-Id: 37 	#Features: 121 	Proc. Time: 2.314ms 
Frame-Id: 38 	#Features: 121 	Proc. Time: 2.354ms 
Frame-Id: 39 	#Features: 121 	Proc. Time: 2.551ms 
Frame-Id: 40 	#Features: 121 	Proc. Time: 2.595ms 
Frame-Id: 41 	#Features: 121 	Proc. Time: 2.297ms 
Frame-Id: 42 	#Features: 121 	Proc. Time: 2.514ms 
Frame-Id: 43 	#Features: 121 	Proc. Time: 1.992ms 
Frame-Id: 44 	#Features: 121 	Proc. Time: 2.351ms 
Frame-Id: 45 	#Features: 121 	Proc. Time: 2.485ms 
Frame-Id: 46 	#Features: 121 	Proc. Time: 2.461ms 
Frame-Id: 47 	#Features: 121 	Proc. Time: 2.214ms 
Frame-Id: 48 	#Features: 121 	Proc. Time: 2.555ms 
Frame-Id: 49 	#Features: 121 	Proc. Time: 2.598ms 
Frame-Id: 50 	#Features: 121 	Proc. Time: 2.347ms 
Frame-Id: 51 	#Features: 121 	Proc. Time: 2.391ms 
Frame-Id: 52 	#Features: 121 	Proc. Time: 2.159ms 
Frame-Id: 53 	#Features: 121 	Proc. Time: 2.134ms 
Frame-Id: 54 	#Features: 121 	Proc. Time: 2.173ms 
Frame-Id: 55 	#Features: 121 	Proc. Time: 2.163ms 
Frame-Id: 56 	#Features: 121 	Proc. Time: 2.359ms 
Frame-Id: 57 	#Features: 121 	Proc. Time: 2.251ms 
Frame-Id: 58 	#Features: 121 	Proc. Time: 2.36ms 
Frame-Id: 59 	#Features: 121 	Proc. Time: 2.314ms 
Frame-Id: 60 	#Features: 121 	Proc. Time: 2.236ms 
Frame-Id: 61 	#Features: 121 	Proc. Time: 2.143ms 
Frame-Id: 62 	#Features: 121 	Proc. Time: 2.425ms 
Frame-Id: 63 	#Features: 121 	Proc. Time: 2.297ms 
Frame-Id: 64 	#Features: 121 	Proc. Time: 2.288ms 
Frame-Id: 65 	#Features: 121 	Proc. Time: 2.216ms 
Frame-Id: 66 	#Features: 121 	Proc. Time: 2.32ms 
Frame-Id: 67 	#Features: 121 	Proc. Time: 2.147ms 
Frame-Id: 68 	#Features: 121 	Proc. Time: 2.441ms 
Frame-Id: 69 	#Features: 121 	Proc. Time: 1.953ms 
Frame-Id: 70 	#Features: 121 	Proc. Time: 2.292ms 
Frame-Id: 71 	#Features: 121 	Proc. Time: 2.021ms 
Frame-Id: 72 	#Features: 121 	Proc. Time: 2.244ms 
Frame-Id: 73 	#Features: 121 	Proc. Time: 2.379ms 
Frame-Id: 74 	#Features: 121 	Proc. Time: 2.468ms 
Frame-Id: 75 	#Features: 121 	Proc. Time: 2.005ms 
Frame-Id: 76 	#Features: 121 	Proc. Time: 2.369ms 
Frame-Id: 77 	#Features: 121 	Proc. Time: 2.12ms 
Frame-Id: 78 	#Features: 121 	Proc. Time: 2.524ms 
Frame-Id: 79 	#Features: 121 	Proc. Time: 2.173ms 
Frame-Id: 80 	#Features: 121 	Proc. Time: 2.407ms 
Frame-Id: 81 	#Features: 121 	Proc. Time: 2.17ms 
Frame-Id: 82 	#Features: 121 	Proc. Time: 2.201ms 
Frame-Id: 83 	#Features: 121 	Proc. Time: 1.883ms 
Frame-Id: 84 	#Features: 121 	Proc. Time: 2.171ms 
Frame-Id: 85 	#Features: 121 	Proc. Time: 2.343ms 
Frame-Id: 86 	#Features: 121 	Proc. Time: 2.36ms 
Frame-Id: 87 	#Features: 121 	Proc. Time: 2.375ms 
Frame-Id: 88 	#Features: 121 	Proc. Time: 2.257ms 
Frame-Id: 89 	#Features: 121 	Proc. Time: 2.077ms 
Frame-Id: 90 	#Features: 121 	Proc. Time: 2.597ms 
Frame-Id: 91 	#Features: 121 	Proc. Time: 2.158ms 
Frame-Id: 92 	#Features: 121 	Proc. Time: 2.425ms 
Frame-Id: 93 	#Features: 121 	Proc. Time: 1.916ms 
Frame-Id: 94 	#Features: 121 	Proc. Time: 2.316ms 
Frame-Id: 95 	#Features: 121 	Proc. Time: 2.297ms 
Frame-Id: 96 	#Features: 121 	Proc. Time: 2.475ms 
Frame-Id: 97 	#Features: 121 	Proc. Time: 2.24ms 
Frame-Id: 98 	#Features: 121 	Proc. Time: 2.419ms 
Frame-Id: 99 	#Features: 121 	Proc. Time: 2.172ms 
Frame-Id: 100 	#Features: 121 	Proc. Time: 2.171ms 
Frame-Id: 101 	#Features: 121 	Proc. Time: 2.31ms 
Frame-Id: 102 	#Features: 121 	Proc. Time: 2.309ms 
Frame-Id: 103 	#Features: 121 	Proc. Time: 2.427ms 
Frame-Id: 104 	#Features: 121 	Proc. Time: 2.589ms 
Frame-Id: 105 	#Features: 121 	Proc. Time: 2.448ms 
Frame-Id: 106 	#Features: 121 	Proc. Time: 2.176ms 
Frame-Id: 107 	#Features: 121 	Proc. Time: 2.638ms 
Frame-Id: 108 	#Features: 121 	Proc. Time: 2.471ms 
Frame-Id: 109 	#Features: 121 	Proc. Time: 2.149ms 
Frame-Id: 110 	#Features: 121 	Proc. Time: 2.46ms 
Frame-Id: 111 	#Features: 121 	Proc. Time: 2.64ms 
Frame-Id: 112 	#Features: 121 	Proc. Time: 2.383ms 
Frame-Id: 113 	#Features: 121 	Proc. Time: 2.488ms 
Frame-Id: 114 	#Features: 121 	Proc. Time: 2.676ms 
Frame-Id: 115 	#Features: 121 	Proc. Time: 2.182ms 
Frame-Id: 116 	#Features: 121 	Proc. Time: 2.546ms 
Frame-Id: 117 	#Features: 121 	Proc. Time: 2.317ms 
Frame-Id: 118 	#Features: 121 	Proc. Time: 2.589ms 
Frame-Id: 119 	#Features: 121 	Proc. Time: 2.27ms 
Frame-Id: 120 	#Features: 121 	Proc. Time: 2.174ms 
Frame-Id: 121 	#Features: 121 	Proc. Time: 2.603ms 
Frame-Id: 122 	#Features: 121 	Proc. Time: 2.396ms 
Frame-Id: 123 	#Features: 121 	Proc. Time: 2.251ms 
Frame-Id: 124 	#Features: 121 	Proc. Time: 2.278ms 
Frame-Id: 125 	#Features: 121 	Proc. Time: 2.265ms 
Frame-Id: 126 	#Features: 121 	Proc. Time: 2.286ms 
Frame-Id: 127 	#Features: 121 	Proc. Time: 2.204ms 
Frame-Id: 128 	#Features: 121 	Proc. Time: 2.662ms 
Frame-Id: 129 	#Features: 121 	Proc. Time: 2.296ms 
Frame-Id: 130 	#Features: 121 	Proc. Time: 2.269ms 
Frame-Id: 131 	#Features: 121 	Proc. Time: 2.098ms 
Frame-Id: 132 	#Features: 121 	Proc. Time: 2.458ms 
Frame-Id: 133 	#Features: 121 	Proc. Time: 2.039ms 
Frame-Id: 134 	#Features: 121 	Proc. Time: 2.583ms 
Frame-Id: 135 	#Features: 121 	Proc. Time: 1.983ms 
Frame-Id: 136 	#Features: 121 	Proc. Time: 2.443ms 
Frame-Id: 137 	#Features: 121 	Proc. Time: 2.4ms 
Frame-Id: 138 	#Features: 121 	Proc. Time: 2.424ms 
Frame-Id: 139 	#Features: 121 	Proc. Time: 2.421ms 
Frame-Id: 140 	#Features: 121 	Proc. Time: 2.624ms 
Frame-Id: 141 	#Features: 121 	Proc. Time: 2.179ms 
Frame-Id: 142 	#Features: 121 	Proc. Time: 2.288ms 
Frame-Id: 143 	#Features: 121 	Proc. Time: 2.057ms 
Frame-Id: 144 	#Features: 121 	Proc. Time: 2.447ms 
Frame-Id: 145 	#Features: 121 	Proc. Time: 2.528ms 
Frame-Id: 146 	#Features: 121 	Proc. Time: 2.401ms 
Frame-Id: 147 	#Features: 121 	Proc. Time: 2.277ms 
Frame-Id: 148 	#Features: 121 	Proc. Time: 2.265ms 
Frame-Id: 149 	#Features: 121 	Proc. Time: 2.196ms 
Frame-Id: 150 	#Features: 121 	Proc. Time: 2.35ms 
Frame-Id: 151 	#Features: 121 	Proc. Time: 2.227ms 
Frame-Id: 152 	#Features: 121 	Proc. Time: 2.357ms 
Frame-Id: 153 	#Features: 121 	Proc. Time: 2.326ms 
Frame-Id: 154 	#Features: 121 	Proc. Time: 2.273ms 
Frame-Id: 155 	#Features: 121 	Proc. Time: 2.254ms 
Frame-Id: 156 	#Features: 121 	Proc. Time: 2.186ms 
Frame-Id: 157 	#Features: 121 	Proc. Time: 2.055ms 
Frame-Id: 158 	#Features: 121 	Proc. Time: 2.108ms 
Frame-Id: 159 	#Features: 121 	Proc. Time: 2.201ms 
Frame-Id: 160 	#Features: 121 	Proc. Time: 2.189ms 
Frame-Id: 161 	#Features: 121 	Proc. Time: 2.286ms 
Frame-Id: 162 	#Features: 121 	Proc. Time: 2.476ms 
Frame-Id: 163 	#Features: 121 	Proc. Time: 2.342ms 
Frame-Id: 164 	#Features: 121 	Proc. Time: 2.472ms 
Frame-Id: 165 	#Features: 121 	Proc. Time: 2.123ms 
Frame-Id: 166 	#Features: 121 	Proc. Time: 2.302ms 
Frame-Id: 167 	#Features: 121 	Proc. Time: 1.984ms 
Frame-Id: 168 	#Features: 121 	Proc. Time: 2.135ms 
Frame-Id: 169 	#Features: 121 	Proc. Time: 2.458ms 
Frame-Id: 170 	#Features: 121 	Proc. Time: 2.574ms 
Frame-Id: 171 	#Features: 121 	Proc. Time: 2.692ms 
Frame-Id: 172 	#Features: 121 	Proc. Time: 3.137ms 
Frame-Id: 173 	#Features: 121 	Proc. Time: 2.449ms 
Frame-Id: 174 	#Features: 121 	Proc. Time: 3.078ms 
Frame-Id: 175 	#Features: 121 	Proc. Time: 2.696ms 
Frame-Id: 176 	#Features: 121 	Proc. Time: 2.792ms 
Frame-Id: 177 	#Features: 121 	Proc. Time: 2.916ms 
Frame-Id: 178 	#Features: 121 	Proc. Time: 2.6ms 
Frame-Id: 179 	#Features: 121 	Proc. Time: 2.681ms 
Frame-Id: 180 	#Features: 121 	Proc. Time: 2.448ms 
Frame-Id: 181 	#Features: 121 	Proc. Time: 2.62ms 
Frame-Id: 182 	#Features: 121 	Proc. Time: 2.664ms 
Frame-Id: 183 	#Features: 121 	Proc. Time: 2.509ms 
Frame-Id: 184 	#Features: 121 	Proc. Time: 2.843ms 
Frame-Id: 185 	#Features: 121 	Proc. Time: 2.445ms 
[INFO] DepthFilter stop thread invoked.
[INFO] DepthFilter interrupt and join thread... 
[INFO] DepthFilter destructed.
[INFO] SVO destructor invoked
[INFO] Map destructed
BenchmarkNode finished.

Is this correct? Where are results? I am pretty new to this and really cant find any results or anything at all.

Thank you so much!
Jakub

**Comment by kubiak54** [comment]
OpenCV was the issue - There was some clash between normally installed OpenCV and ROS-provided one. Reinstalling Ubuntu and ROS without installing OpenCV solely solved ROS issue.
