### ISSUE TITLE
Crash on launch ARM, backtrace points libc

### ISSUE THREAD

**Issue by AlexisTM** [uzh-rpg/rpg_svo#165]
Dear, 

I am experimenting with rpg_svo (actual master) on ARMv7, but I got one error when launching live.launch. The problem is similar to #42 but the backtrace is pointing libc. How should I resolve the problem, upgrade gcc ? Recompile glibc ?

NOTE : It works with the dataset...

> *** Error in `/home/odroid/Workspace/SVO_Catkin/devel/lib/svo_ros/vo': free(): invalid next size (normal): 0x00208180 ***

setup : 
* Odroid XU4
* Ubuntu 14.04
* ROS Indigo
* gcc 4:4.8.2-1ubuntu6 

live.launch
```xml
<launch>
  <node name="usb_cam" pkg="usb_cam" type="usb_cam_node" output="screen" >
    <param name="video_device" value="/dev/video0" />
    <param name="image_width" value="640" />
    <param name="image_height" value="360" />
    <param name="pixel_format" value="yuyv" />
    <param name="camera_frame_id" value="usb_cam" />
    <param name="io_method" value="mmap"/>
  </node>

  <node name="image_proc" pkg="image_proc" type="image_proc">
    <remap from="image_raw" to="/usb_cam/image_raw" />
    <remap from="camera_info" to="/usb_cam/camera_info" />
  </node>

  <node pkg="svo_ros" launch-prefix="gdb -ex run --args" type="vo" name="svo" clear_params="true" output="screen">
    <param name="cam_topic" value="$(optenv IMAGE /image_mono)"/>
    <rosparam file="$(find svo_ros)/param/odroid360p.yaml" />
    <param name="init_rx" value="3.14" />
    <param name="init_ry" value="0" />
    <param name="init_rz" value="0" />
    <param name="init_tx" value="0" />
    <param name="init_ty" value="0" />
    <param name="init_tz" value="0" />
    <!-- Default parameter settings: choose between vo_fast and vo_accurate -->
    <rosparam file="$(find svo_ros)/param/vo_fast.yaml" />
  </node>

</launch>
```

backtrace
```bash
[ INFO] [1474250400.139690540]: Found parameter: svo/cam_topic, value: /image_mono
[ INFO] [1474250400.777540936]: RESET
*** Error in `/home/odroid/Workspace/SVO_Catkin/devel/lib/svo_ros/vo': free(): invalid next size (normal): 0x00208180 ***

Program received signal SIGABRT, Aborted.
__libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
44	../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0xb69fa0fe in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb69fc956 in __GI_abort () at abort.c:89
#3  0xb6a20de0 in __libc_message (do_abort=<optimized out>,
    fmt=0xb6aa22b8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#4  0xb6a2798e in malloc_printerr (action=1,
    str=0xb6aa2474 "free(): invalid next size (normal)", ptr=<optimized out>) at malloc.c:4996
#5  0xb6a283b4 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0)
    at malloc.c:3840
#6  0xb6d5387c in deallocate (this=<optimized out>, __p=<optimized out>)
    at /usr/include/c++/4.8/ext/new_allocator.h:110
#7  _M_deallocate (this=<optimized out>, __n=<optimized out>, __p=<optimized out>)
    at /usr/include/c++/4.8/bits/stl_vector.h:174
#8  ~_Vector_base (this=0xbeffd734, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/bits/stl_vector.h:160
#9  ~vector (this=0xbeffd734, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/bits/stl_vector.h:416
#10 svo::feature_detection::FastDetector::detect (this=this@entry=0xbeffd7b0,
    frame=frame@entry=0x1b09a0, img_pyr=..., detection_threshold=20, fts=...)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/feature_detection.cpp:90
#11 0xb6d4f03c in svo::initialization::detectFeatures (frame=..., px_vec=..., f_vec=...)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/initialization.cpp:115
#12 0xb6d4f20a in svo::initialization::KltHomographyInit::addFirstFrame (this=0x1ad408,
    frame_ref=...)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/initialization.cpp:32
#13 0xb6d41566 in svo::FrameHandlerMono::processFirstFrame (this=0x1ad1a0)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/frame_handler_mono.cpp:95
#14 0xb6d4374e in svo::FrameHandlerMono::addImage (this=0x1ad1a0, img=...,
    timestamp=20.000010024723284)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/frame_handler_mono.cpp:79
#15 0x00012a0e in svo::VoNode::imgCb(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&) ()
#16 0xaeda01d6 in image_transport::RawSubscriber::internalCallback(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::function<void (boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)> const&) ()
   from /opt/ros/indigo/lib//libimage_transport_plugins.so
#17 0xb6dc6698 in boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const>) ()
   from /opt/ros/indigo/lib/libimage_transport.so
#18 0xaeda2d10 in ros::SubscriptionCallbackHelperT<boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) ()
   from /opt/ros/indigo/lib//libimage_transport_plugins.so
#19 0xb6cb1580 in ros::SubscriptionQueue::call() () from /opt/ros/indigo/lib/libroscpp.so
#20 0xb6c82f12 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) ()
   from /opt/ros/indigo/lib/libroscpp.so
#21 0xb6c83610 in ros::CallbackQueue::callAvailable(ros::WallDuration) ()
   from /opt/ros/indigo/lib/libroscpp.so
#22 0xb6ca35fe in ros::spinOnce() () from /opt/ros/indigo/lib/libroscpp.so
#23 0x00011d4e in main ()

```

**Comment by AlexisTM** [comment]
I tested after upgrading GCC to 4.9, same error : 

backtrace 

```
*** Error in `/home/odroid/Workspace/SVO_Catkin/devel/lib/svo_ros/vo': free(): invalid next size (normal): 0x002083c8 ***

Program received signal SIGABRT, Aborted.
__libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
44      ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0xb69e20fe in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb69e4956 in __GI_abort () at abort.c:89
#3  0xb6a08de0 in __libc_message (do_abort=<optimized out>, fmt=0xb6a8a2b8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#4  0xb6a0f98e in malloc_printerr (action=1, str=0xb6a8a474 "free(): invalid next size (normal)",
    ptr=<optimized out>) at malloc.c:4996
#5  0xb6a103b4 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#6  0xb6d50634 in deallocate (this=<optimized out>, __p=0x2083c8) at /usr/include/c++/4.9/ext/new_allocator.h:110
#7  deallocate (__a=..., __n=<optimized out>, __p=0x2083c8) at /usr/include/c++/4.9/bits/alloc_traits.h:514
#8  _M_deallocate (this=<optimized out>, __n=<optimized out>, __p=0x2083c8)
    at /usr/include/c++/4.9/bits/stl_vector.h:178
#9  ~_Vector_base (this=0xbeffdc8c, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/stl_vector.h:160
#10 ~vector (this=0xbeffdc8c, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/stl_vector.h:425
#11 svo::feature_detection::FastDetector::detect (this=this@entry=0xbeffdd00, frame=frame@entry=0x1f2d80,
    img_pyr=..., detection_threshold=20, fts=...)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/feature_detection.cpp:90
#12 0xb6d4b388 in svo::initialization::detectFeatures (frame=..., px_vec=..., f_vec=...)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/initialization.cpp:115
#13 0xb6d4b53e in svo::initialization::KltHomographyInit::addFirstFrame (this=0x1b3c68, frame_ref=...)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/initialization.cpp:32
#14 0xb6d3d3a6 in svo::FrameHandlerMono::processFirstFrame (this=0x1b3a00)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/frame_handler_mono.cpp:95
#15 0xb6d3d9d2 in svo::FrameHandlerMono::addImage (this=0x1b3a00, img=..., timestamp=1474259325.965286)
    at /home/odroid/Workspace/SVO_Catkin/src/rpg_svo/svo/src/frame_handler_mono.cpp:79
#16 0x000136d8 in svo::VoNode::imgCb(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&) ()
#17 0xaedb51d6 in image_transport::RawSubscriber::internalCallback(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::function<void (boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)> const&) () from /opt/ros/indigo/lib//libimage_transport_plugins.so
#18 0xb6dc4698 in boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const>) () from /opt/ros/indigo/lib/libimage_transport.so
#19 0xaedb7d10 in ros::SubscriptionCallbackHelperT<boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) ()
   from /opt/ros/indigo/lib//libimage_transport_plugins.so
#20 0xb6cab580 in ros::SubscriptionQueue::call() () from /opt/ros/indigo/lib/libroscpp.so
#21 0xb6c7cf12 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/indigo/lib/libroscpp.so
#22 0xb6c7d610 in ros::CallbackQueue::callAvailable(ros::WallDuration) () from /opt/ros/indigo/lib/libroscpp.so
#23 0xb6c9d5fe in ros::spinOnce() () from /opt/ros/indigo/lib/libroscpp.so
#24 0x000129c0 in main ()
(gdb)
```

**Comment by AlexisTM** [comment]
News : 

It is not the camera, but maybe an expected camera size. I forced my camera to be 752x480 and the algorithm started, while, with same parameters, 640x360 do not work.

NOTE : The camera is incompatible with 752x480 thus the resulting image is absolutely incoherent and is unusable.

**Comment by AlexisTM** [comment]
Outdated.
